name: Check Branch Name

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          echo "Current branch: $BRANCH_NAME"
          
          if [[ $BRANCH_NAME == feature/* ]]; then
            echo "Branch name is valid."
          else
            echo "Error: Branch name must start with 'feature/'"
            exit 1
          fi
